### PR TITLE
Data dirs further

### PR DESCRIPTION
**Pull request by rgbkrk**
This provides `~/.ipython` as a directory to check for kernels.

Since this repository (and `ipython-paths` originally) has been around since the early beginnings of nteract I also allowed prettier to run over `index.js`. The most important commit to look at for review is the last one.

### CODE REVIEW

**Comment by rgbkrk** [comment]
For the longest time I've been trying not to allow the legacy directory, instead hoping that iruby would get updates to use the proper jupyter directories. I'm kind of leaning towards just allowing it anyways.

cc @minrk @alexandercbooth @BenRussert

**Comment by rgbkrk** [comment]
Addressing the tests will make me super sad, as we're actually checking conformance against `jupyter` itself.

**Comment by captainsafia** [comment]
Hmmmm. We'll need to address this case in fs-kernels now.

**Comment by rgbkrk** [comment]
Oh did you discover this somewhere? I think only with iruby I've had to handle this case.

**Pull request closed without merging**
