### PR TITLE
Fix AppVeyor build

### PR DESCRIPTION
**Pull request by lgeiger**

### CODE REVIEW

**Comment by lgeiger** [comment]
~~This will convert the paths to lowercase before comparing them.~~

**Comment by lgeiger** [comment]
I just saw @minrk fixed this in #15 already. I'm removing my changes to prevent merge conflicts. So AppVeyor will still fail on this PR.

**Comment by rgbkrk** [comment]
It looks the only change that needs to be addressed is casing on the `C:` drive in the tests.

**Comment by lgeiger** [comment]
@rgbkrk That's right. But I removed my fixes to prevent merge conflicts with [#15](https://github.com/nteract/jupyter-paths/pull/15/commits/5a3fc265508a44b83255438b9600e20d11f67829)

Here is the working build: https://ci.appveyor.com/project/nteract/jupyter-paths/build/1.0.6

**Pull request merged**
