### PR TITLE
Add appveyor.yaml

### PR DESCRIPTION
**Pull request by captainsafia**
nteract ❤️s [Windows](https://www.youtube.com/watch?v=Ml_eZPDEEms).

Not sure how much we want our build matrix to cover.

Addresses #11.

### CODE REVIEW

**Comment by captainsafia** [comment]
Good to merge.

**Comment by rgbkrk** [comment]
It looks like if the path checking in the tests was case insensitive this would work on at least one of the environments.

**Comment by rgbkrk** [comment]
> Not sure how much we want our build matrix to cover.

To reduce complexity here, I'd only test 64-bit Windows. If at all possible, I'd only aim for getting one to work cleanly here first.

**Comment by rgbkrk** [comment]
Since the casing issue is captured in #14 and the logs are pretty clear, we can assume that we'll tackle it at some point instead of letting this sit.

Thanks @captainsafia!

**Pull request merged**
